# This an autogenerated file
# 
# Generated with SIFImportConfiguration
from typing import Dict,Sequence,List
from dmt.blueprint import Blueprint
from .blueprints.sifimportconfiguration import SIFImportConfigurationBlueprint
from typing import Dict
from ..sima import MOAO
from ..sima import ScriptableValue
from .qtfimportoption import QTFImportOption
from .retardationfunctioncalculationparameters import RetardationFunctionCalculationParameters
from .secondorderwavedriftoption import SecondOrderWaveDriftOption

class SIFImportConfiguration(MOAO):
    """
    Keyword arguments
    -----------------
    description : str
         (default "")
    scriptableValues : List[ScriptableValue]
    taskName : str
         Name of task to import into. Required if bodyName is set.(default None)
    bodyName : str
         Optional. Name of SIMOBody to merge hydrodynamic data into.(default None)
    waveDriftOption : SecondOrderWaveDriftOption
    qtfImportOption : QTFImportOption
    retardationFunctionParameters : RetardationFunctionCalculationParameters
    """

    def __init__(self , description="", waveDriftOption=SecondOrderWaveDriftOption.COMBINED, qtfImportOption=QTFImportOption.ANY, **kwargs):
        super().__init__(**kwargs)
        self.description = description
        self.scriptableValues = list()
        self.taskName = None
        self.bodyName = None
        self.waveDriftOption = waveDriftOption
        self.qtfImportOption = qtfImportOption
        self.retardationFunctionParameters = None
        for key, value in kwargs.items():
            if not isinstance(value, Dict):
                setattr(self, key, value)


    @property
    def blueprint(self) -> Blueprint:
        """Return blueprint that this entity represents"""
        return SIFImportConfigurationBlueprint()


    @property
    def description(self) -> str:
        """"""
        return self.__description

    @description.setter
    def description(self, value: str):
        """Set description"""
        self.__description = value

    @property
    def scriptableValues(self) -> List[ScriptableValue]:
        """"""
        return self.__scriptableValues

    @scriptableValues.setter
    def scriptableValues(self, value: List[ScriptableValue]):
        """Set scriptableValues"""
        if not isinstance(value, Sequence):
            raise ValueError("Expected sequense, but was " , type(value))
        self.__scriptableValues = value

    @property
    def taskName(self) -> str:
        """Name of task to import into. Required if bodyName is set."""
        return self.__taskName

    @taskName.setter
    def taskName(self, value: str):
        """Set taskName"""
        self.__taskName = value

    @property
    def bodyName(self) -> str:
        """Optional. Name of SIMOBody to merge hydrodynamic data into."""
        return self.__bodyName

    @bodyName.setter
    def bodyName(self, value: str):
        """Set bodyName"""
        self.__bodyName = value

    @property
    def waveDriftOption(self) -> SecondOrderWaveDriftOption:
        """"""
        return self.__waveDriftOption

    @waveDriftOption.setter
    def waveDriftOption(self, value: SecondOrderWaveDriftOption):
        """Set waveDriftOption"""
        self.__waveDriftOption = value

    @property
    def qtfImportOption(self) -> QTFImportOption:
        """"""
        return self.__qtfImportOption

    @qtfImportOption.setter
    def qtfImportOption(self, value: QTFImportOption):
        """Set qtfImportOption"""
        self.__qtfImportOption = value

    @property
    def retardationFunctionParameters(self) -> RetardationFunctionCalculationParameters:
        """"""
        return self.__retardationFunctionParameters

    @retardationFunctionParameters.setter
    def retardationFunctionParameters(self, value: RetardationFunctionCalculationParameters):
        """Set retardationFunctionParameters"""
        self.__retardationFunctionParameters = value
