# This an autogenerated file
# 
# Generated with RIFLEXLocation
from typing import Dict,Sequence,List
from dmt.blueprint import Blueprint
from .blueprints.riflexlocation import RIFLEXLocationBlueprint
from typing import Dict
from ..environment import SeaSurface
from ..sima import FlatBottom
from ..sima import InfrastructureBody
from ..sima import InitialViewpoint
from ..sima import NamedViewpoint
from ..sima import ScriptableValue
from ..simo import CommonLocation
from ..simo import PhysicalConstants
from .densitylevel import DensityLevel
from .regular3dbottom import Regular3DBottom

class RIFLEXLocation(CommonLocation):
    """
    Keyword arguments
    -----------------
    description : str
         (default "")
    scriptableValues : List[ScriptableValue]
    name : str
         (default None)
    initialViewpoint : InitialViewpoint
    viewpoints : List[NamedViewpoint]
    relativeCompassAngle : float
         This is the relative angle measured from the global x-axis to the compass North, measured counter-clockwise(default 0.0)
    infrastructureBodies : List[InfrastructureBody]
    waterDepth : float
         Water depth for kinematics(default 1000.0)
    seaSurface : SeaSurface
    flatBottom : FlatBottom
    physicalConstants : PhysicalConstants
    regular3DBottom : Regular3DBottom
    depthDependentWaterDensity : bool
         (default False)
    densityLevels : List[DensityLevel]
    """

    def __init__(self , description="", relativeCompassAngle=0.0, waterDepth=1000.0, depthDependentWaterDensity=False, **kwargs):
        super().__init__(**kwargs)
        self.description = description
        self.scriptableValues = list()
        self.name = None
        self.initialViewpoint = None
        self.viewpoints = list()
        self.relativeCompassAngle = relativeCompassAngle
        self.infrastructureBodies = list()
        self.waterDepth = waterDepth
        self.seaSurface = None
        self.flatBottom = None
        self.physicalConstants = None
        self.regular3DBottom = None
        self.depthDependentWaterDensity = depthDependentWaterDensity
        self.densityLevels = list()
        for key, value in kwargs.items():
            if not isinstance(value, Dict):
                setattr(self, key, value)


    @property
    def blueprint(self) -> Blueprint:
        """Return blueprint that this entity represents"""
        return RIFLEXLocationBlueprint()


    @property
    def description(self) -> str:
        """"""
        return self.__description

    @description.setter
    def description(self, value: str):
        """Set description"""
        self.__description = value

    @property
    def scriptableValues(self) -> List[ScriptableValue]:
        """"""
        return self.__scriptableValues

    @scriptableValues.setter
    def scriptableValues(self, value: List[ScriptableValue]):
        """Set scriptableValues"""
        if not isinstance(value, Sequence):
            raise ValueError("Expected sequense, but was " , type(value))
        self.__scriptableValues = value

    @property
    def name(self) -> str:
        """"""
        return self.__name

    @name.setter
    def name(self, value: str):
        """Set name"""
        self.__name = value

    @property
    def initialViewpoint(self) -> InitialViewpoint:
        """"""
        return self.__initialViewpoint

    @initialViewpoint.setter
    def initialViewpoint(self, value: InitialViewpoint):
        """Set initialViewpoint"""
        self.__initialViewpoint = value

    @property
    def viewpoints(self) -> List[NamedViewpoint]:
        """"""
        return self.__viewpoints

    @viewpoints.setter
    def viewpoints(self, value: List[NamedViewpoint]):
        """Set viewpoints"""
        if not isinstance(value, Sequence):
            raise ValueError("Expected sequense, but was " , type(value))
        self.__viewpoints = value

    @property
    def relativeCompassAngle(self) -> float:
        """This is the relative angle measured from the global x-axis to the compass North, measured counter-clockwise"""
        return self.__relativeCompassAngle

    @relativeCompassAngle.setter
    def relativeCompassAngle(self, value: float):
        """Set relativeCompassAngle"""
        self.__relativeCompassAngle = float(value)

    @property
    def infrastructureBodies(self) -> List[InfrastructureBody]:
        """"""
        return self.__infrastructureBodies

    @infrastructureBodies.setter
    def infrastructureBodies(self, value: List[InfrastructureBody]):
        """Set infrastructureBodies"""
        if not isinstance(value, Sequence):
            raise ValueError("Expected sequense, but was " , type(value))
        self.__infrastructureBodies = value

    @property
    def waterDepth(self) -> float:
        """Water depth for kinematics"""
        return self.__waterDepth

    @waterDepth.setter
    def waterDepth(self, value: float):
        """Set waterDepth"""
        self.__waterDepth = float(value)

    @property
    def seaSurface(self) -> SeaSurface:
        """"""
        return self.__seaSurface

    @seaSurface.setter
    def seaSurface(self, value: SeaSurface):
        """Set seaSurface"""
        self.__seaSurface = value

    @property
    def flatBottom(self) -> FlatBottom:
        """"""
        return self.__flatBottom

    @flatBottom.setter
    def flatBottom(self, value: FlatBottom):
        """Set flatBottom"""
        self.__flatBottom = value

    @property
    def physicalConstants(self) -> PhysicalConstants:
        """"""
        return self.__physicalConstants

    @physicalConstants.setter
    def physicalConstants(self, value: PhysicalConstants):
        """Set physicalConstants"""
        self.__physicalConstants = value

    @property
    def regular3DBottom(self) -> Regular3DBottom:
        """"""
        return self.__regular3DBottom

    @regular3DBottom.setter
    def regular3DBottom(self, value: Regular3DBottom):
        """Set regular3DBottom"""
        self.__regular3DBottom = value

    @property
    def depthDependentWaterDensity(self) -> bool:
        """"""
        return self.__depthDependentWaterDensity

    @depthDependentWaterDensity.setter
    def depthDependentWaterDensity(self, value: bool):
        """Set depthDependentWaterDensity"""
        self.__depthDependentWaterDensity = bool(value)

    @property
    def densityLevels(self) -> List[DensityLevel]:
        """"""
        return self.__densityLevels

    @densityLevels.setter
    def densityLevels(self, value: List[DensityLevel]):
        """Set densityLevels"""
        if not isinstance(value, Sequence):
            raise ValueError("Expected sequense, but was " , type(value))
        self.__densityLevels = value
