name: Testing

on: [push]

jobs:
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build Docker Images"
        run: docker-compose build simapy
      - name: "Tests"
        run: docker-compose run simapy pytest --junitxml output/report.xml
